-- 012 — Rename the negative-forward signal from ANOMALOUS to FRONT_LOADED.
--
-- A negative implied forward arises whenever f_far * t_far < f_near * t_near --
-- a steeply falling fee curve -- and on real data that is about a quarter of all
-- tenor pairs. Calling a quarter of the market "anomalous" was wrong: it means
-- the entire cost of the borrow sits in the near window and the market expects
-- the tail to be nearly free. That is a finding, not a data error.
--
-- It is also not an arbitrage, which is why the old name was actively
-- misleading. The no-arbitrage forward assumes the near contract can be rolled
-- AT the forward; in SLB it cannot, because rolling means trading a fresh
-- contract at a new market-determined fee and NCL facilitates rollover on a
-- best-efforts basis only. The forward is an expectation the market is pricing,
-- not a rate anyone can lock.
--
-- A separate migration rather than an edit to 011, because scripts/migrate.py
-- checksums applied migrations and refuses a changed one (ADR 0002). It caught
-- the first attempt at exactly that.

-- Derived rows, regenerated by `make analytics`, so clearing them is safe and is
-- required before the tighter constraint can be installed.
DELETE FROM slb_implied_forward;

ALTER TABLE slb_implied_forward DROP CONSTRAINT slb_implied_forward_signal_check;

ALTER TABLE slb_implied_forward ADD CONSTRAINT slb_implied_forward_signal_check
    CHECK (signal IN ('RESOLVING', 'PERSISTENT', 'WORSENING', 'FRONT_LOADED', 'FLAT'));
